name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: latest
      
      - name: Test signing (without publishing)
        run: |
          # This will test if secrets are accessible without actually publishing
          earthly +sign --version=test-1.0.0
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
      
      - name: Verify secrets are set
        run: |
          echo "Checking if secrets are available..."
          if [ -z "${{ secrets.CERTIFICATE_CHAIN }}" ]; then
            echo "❌ CERTIFICATE_CHAIN is not set"
            exit 1
          else
            echo "✅ CERTIFICATE_CHAIN is set"
          fi
          
          if [ -z "${{ secrets.PRIVATE_KEY }}" ]; then
            echo "❌ PRIVATE_KEY is not set"
            exit 1
          else
            echo "✅ PRIVATE_KEY is set"
          fi
          
          if [ -z "${{ secrets.PRIVATE_KEY_PASSWORD }}" ]; then
            echo "❌ PRIVATE_KEY_PASSWORD is not set"
            exit 1
          else
            echo "✅ PRIVATE_KEY_PASSWORD is set"
          fi
          
          if [ -z "${{ secrets.PUBLISH_TOKEN }}" ]; then
            echo "⚠️  PUBLISH_TOKEN is not set (optional for signing test)"
          else
            echo "✅ PUBLISH_TOKEN is set"
          fi