name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: earthly/actions/setup-earthly@fb998b3dbcf877575a8f9c1897dd64efb9564176  # v1
        with:
          version: latest
      - name: Run Earthly tests
        run: earthly +test
